### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by cwchristerw** [AseCoder/Futox#1]
Add LICENSE file and you should put same license (SPDX format) in package.json.

SPDX License List: https://spdx.org/licenses/

**Comment by AseCoder** [comment]
done

**Comment by cwchristerw** [comment]
Sorry I want this issue to reopened because ...

Package.json doesn't use spdx format in license because you must specify version number according to SPDX License List. Also I think making source available with license of your choice is not free enough to any people to get this code useful.

CC License is not supposed to be used in open source software
https://creativecommons.org/about/program-areas/software/

You should not use open source word if your license is not OSI Approved. You can find multiple OSI Approved licenses (this page is recommended in above site)
https://opensource.org/licenses/

**Comment by AseCoder** [comment]
> i just scrolled through like 5 pages of open source license and after reading the last ½ page i can safely say i wont add a license anytime soon
_- me, today_

**issue closed, conversation locked**
