### ISSUE TITLE
Add environment variable to disable discordbots.org API

### ISSUE THREAD

**Issue by cwchristerw** [AseCoder/Futox#6]
This makes it easier to test code when contributor is adding or fixing things. This makes it possible to run also development version without running discordbots.org API. :smile:

DISABLE_DBL (could be name of environment variable), also it could be just when DBLTOKEN variable is empty or undefined then DBL is disabled.

**Comment by cwchristerw** [comment]
If you want I can make PR about this.

**Comment by AseCoder** [comment]
yes please make a pr
