### ISSUE TITLE
Core Dev list to separate json file.

### ISSUE THREAD

**Issue by cwchristerw** [AseCoder/Futox#8]
This makes possible to use eval command when someone else is using this source code or when they are testing code.

**Comment by cwchristerw** [comment]
This is also part of #7 because all configuration must be outside of Docker Container making them constant when updating image :smile:

**Comment by AseCoder** [comment]
you have a good idea but i have a better fix.
i plan on creating a new way to define the core dev list. the core dev list most likely will not be available to other people's Futox instances. along with these changes eval permission check will be rewritten.
